# Generated by Django 5.0.6 on 2024-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('steamspy_tags', models.CharField(max_length=255)),
                ('positive_ratings', models.IntegerField()),
                ('negative_ratings', models.IntegerField()),
                ('median_playtime', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('header_image', models.URLField()),
            ],
        ),
    ]
