# Generated by Django 5.0.6 on 2024-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('playtime_forever', models.IntegerField()),
                ('playtime_2weeks', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('median_playtime', models.IntegerField()),
                ('Assuming_Ratings', models.IntegerField()),
                ('user_id', models.CharField(max_length=255)),
                ('user_alias', models.CharField(max_length=255)),
            ],
        ),
    ]
