# Generated by Django 5.0.6 on 2024-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_recommendations', '0002_userrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAliasMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('user_alias', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
