# Generated by Django 5.0.6 on 2024-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_recommendations', '0003_useraliasmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CB_GameRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_alias', models.CharField(max_length=255)),
                ('appid', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CF_GameRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_alias', models.CharField(max_length=255)),
                ('appid', models.IntegerField()),
                ('game_name', models.CharField(max_length=255)),
                ('predicted_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_alias', models.CharField(max_length=255)),
                ('sim_user_id', models.CharField(max_length=255)),
                ('sim_user_alias', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField()),
            ],
        ),
    ]
